### ISSUE TITLE
Unknown alias: SCDW when creating performance collection rule

### ISSUE THREAD

**Issue by MrDibbley** [squaredup/Community.PowerShellMonitoring.MP#1]
Created a new empty management pack

Created a new performance collection rule to collect file size.

When click save the following error is generated:

Date: 20/07/2017 07:54:15
Application: Operations Manager
Application Version: 7.1.10226.1177
Severity: Error
Message: 

: Processing the template failed. See inner exception for details.
Cannot resolve identifier SCDW!Microsoft.SystemCenter.DataWarehouse.PublishPerformanceData in the context of management pack MY.New.MP. Unknown alias: SCDW
: Cannot resolve identifier SCDW!Microsoft.SystemCenter.DataWarehouse.PublishPerformanceData in the context of management pack MY.New.MP. Unknown alias: SCDW

same result on remote console and on management server

Running UR9 2012 R2

**Comment by shadeon** [comment]
Thanks for reporting an issue - will take a look at this now.

**Comment by shadeon** [comment]
This is an issue that was identified and fixed during Technical Preview.  Unfortunately it looks like the build that was published didn't include this fix (Oops!).  I've just updated the released version to the correct build - if you go to the [download page](https://download.squaredup.com/management-packs/powershell-monitoring-management-pack/) you should see the latest version is now 1.1.1 - so grab and import that.

Let us know if you run into any further problems with this, and I'll be happy to re-open the issue.
