### ISSUE TITLE
Add Alert Suppression to Alert Rules

### ISSUE THREAD

**Issue by PowershellNinja** [squaredup/Community.PowerShellMonitoring.MP#4]
As of the current Version, the Alert Rules generated by using this MP in the Console contain an empty
```XML
<Suppression/>
```
Tag - causing no Alert suppression, meaning there is no Repeat Count increase - just a new Alert for every run of the rule.

Please either add the possibility to Configure this through the Wizard, set the Default value to 
```XML
<Suppression>
          <SuppressionValue></SuppressionValue>
</Suppression>
```
to enable Suppression or at least put this into documentation.

**Comment by PowershellNinja** [comment]
Just noticed I was a bit fast and missed the "Alert Suppression" Button on the last Wizard page. Still, I wasn't able to add an empty SuppressionValue resulting in Suppression based on the Workflow ID, how would I do that using the Wizard? Or, do I still have to do that in the XML?

**Comment by shadeon** [comment]
Hi, sorry for the extremely delayed response.

The Alert Suppression screen should allow you to pick suppression properties via the "Add Suppression field" - are you saying If you then click the $Target.. button you don't see a list of properties, or that you specifically want to suppress *all* instances of this alert from *every* source?  In the latter case, you'll need to do that in the XML as a post step (this seems a pretty atypical setup - what's your use case if you don't mind me asking?).

**Comment by PowershellNinja** [comment]
Hi Shadeon
No Problem at all. Yes, the idea was to suppress all instances of the alert but the first per source - and I wasn't able to figure out how to do this without just putting in the empty SuppressionValue (which seemed to work well in our case). On what field would I normally configure the Suppression to suppress all alerts from all sources - but the first one from each source?

**Comment by shadeon** [comment]
Typically you'd pick the key properties for the class instance the rule targets - for computer bound objects with a single object per hosting parent (most Computer Roles, for example) you'll just select the PrincipalName.  

For something like a SQL database you'd want the Principal name, Instance and Database Name since if all three are the unique you know it's the same database and can suppress repeating instances of the alert.

**Comment by PowershellNinja** [comment]
I see, thanks for the explanation, I'll close the issue as this answers my questions.

Thanks for your assistance!
